[package]
name = "iml-manager-client"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
iml-manager-env = { path = "../iml-manager-env", version = "0.1.0" }
reqwest = { git = "https://github.com/seanmonstar/reqwest", features = ["default-tls", "tls", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
url = "2.1"