[package]
name = "iml-mailbox"
version = "0.3.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
futures = "0.3"
iml-fs = { path = "../iml-fs", version = "0.3" }
iml-manager-env = { path = "../iml-manager-env", version = "0.3" }
iml-tracing = { version = "0.2", path="../iml-tracing"}
tokio = "0.2"
tracing = "0.1"
warp = "0.2"

[dev-dependencies]
tempdir = "0.3"