[package]
name = "iml-mailbox"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
futures-preview = "0.3.0-alpha.19"
iml-manager-env = { path = "../iml-manager-env", version = "0.1.0" }
iml-fs = { path = "../iml-fs", version = "0.1" }
tokio = "0.2.0-alpha.6"
warp = { git = "https://github.com/seanmonstar/warp.git" }
tracing = "0.1"
tracing-subscriber = "0.1"

[dev-dependencies]
pretty_assertions = "0.6.1"
tempdir = "0.3"