[package]
name = "iml-mailbox"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
env_logger = "0.6"
futures = "0.1"
log = "0.4"
iml-manager-env = { path = "../iml-manager-env", version = "0.1.0" }
stream-lines = { git = "https://github.com/softprops/stream-lines" }
warp = "0.1" 