[package]
version = "0.1.0"
name = "iml-gui"
repository = "https://github.com/whamcloud/integrated-manager-for-lustre"
authors = ["IML Team <iml@whamcloud.com>"]
description = "The IML GUI"
categories = ["wasm", "rust", "tailwindcss", "seed"]
license = "MIT"
readme = "./README.md"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
wasm-bindgen-test = "0.3"
rand_core = "0.5.1"
rand_xoshiro = "0.4.0"

[dependencies]
chrono = { version = "0.4", features = ["wasmbind"] }
chrono-humanize = "0.0.11"
futures = "0.3"
gloo-timers = { version = "0.2", features = ["futures"] }
im = { version = "14.3", features = ["serde"] }
iml-api-utils = { path = "../../iml-api-utils", version = "0.2" }
iml-influx = { path = "../../iml-influx", version = "0.1" }
iml-wire-types = { path = "../../iml-wire-types", version = "0.2" }
js-sys = "0.3"
lazy_static = "1.4.0"
natord = "1.0"
number-formatter = { path = "../../number-formatter", version = "0.1" }
seed = "0.6.0"
serde = { version = "1", features = ['derive'] }
serde_json = "1.0"
serde_urlencoded = "0.6.1"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[dependencies.regex]
version = "1.3"
default-features = false
features = ["std", "unicode-perl"]

[dependencies.web-sys]
version = "^0.3"
features = [
  "DomRect",
  "Element",
  "EventSource",
  "HtmlDocument",
  "MessageEvent",
  "Navigator",
  "Notification",
  "NotificationOptions",
  "NotificationPermission",
  "ServiceWorkerContainer",

  "ServiceWorkerRegistration",
  "Window",
]

[profile.release]
lto = true
opt-level = 's'
