[package]
name = "iml-ostpool"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.19"
iml-postgres = { path = "../../iml-postgres", version = "0.1.0" }
iml-service-queue = { path = "../iml-service-queue", version = "0.1.0" }
iml-wire-types = { path = "../../iml-wire-types", version = "0.2" }
tokio = "0.2.0-alpha.6"
tracing = "0.1"
tracing-subscriber = "0.1"
