[package]
name = "iml-warp-drive"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
lapin-futures = "0.18.0"
futures = "0.1.26"
tokio = "0.1.18"
env_logger = "0.6.1"
log = "0.4.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1.5"
uuid = { version = "0.7", features = ["v4"] }
warp = "0.1"
parking_lot = "0.7"
iml-manager-env = { path = "../iml-manager-env", version = "0.1.0" }
iml-rabbit = { path = "../iml-rabbit", version = "0.1.0" }