[package]
name = "iml-warp-drive"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
lapin-futures = "0.18.0"
futures01 = { package = "futures", version = "0.1" }
futures-preview = { version = "=0.3.0-alpha.19", features = ["compat"]}
tokio = "0.1"
env_logger = "0.6"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
failure = "0.1.5"
uuid = { version = "0.7", features = ["v4"] }
warp = "0.1"
parking_lot = "0.9"
iml-manager-env = { path = "../iml-manager-env", version = "0.1.0" }
iml-rabbit = { path = "../iml-rabbit", version = "0.1.0" }
iml-postgres = { path = "../iml-postgres", version = "0.1.0" }
iml-wire-types = { path = "../iml-wire-types", version = "0.1", features = ["postgres-interop"] }
iml-manager-client-1 = { path = "../iml-manager-client-1", version = "0.1" }
tokio-runtime-shutdown = { path = "../tokio-runtime-shutdown", version = "0.1" }