[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
license = "MIT"
name = "mount-emitter"
version = "0.2.0"

[[bin]]
name = "mount-emitter"
path = "src/bin/mount_emitter.rs"

[dependencies]
device-types = {path = "../device-types", version = "0.3.0"}
futures = "0.1"
serde_json = "1.0"
tokio = "0.1"
tokio-file-unix = "0.5.1"

[dev-dependencies]
insta = "0.11"
pretty_assertions = "0.6.1"
tokio-mockstream = "1.1"
