[package]
name = "iml-stats"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
iml-service-queue = { path = "../iml-service-queue", version = "0.1.0" }
iml-wire-types = { path = "../../iml-wire-types", version = "0.2" }
influxdb = "0.0.6"
lustre_collector = "0.2.5"
tokio = "0.2"
tracing = "0.1"
tracing-subscriber = "0.2"
iml-manager-env = { path = "../../iml-manager-env", version = "0.1.0" }