[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-stats"
version = "0.3.0"

[dependencies]
futures = "0.3"
iml-manager-env = {path = "../../iml-manager-env", version = "0.3"}
iml-rabbit = {path = "../../iml-rabbit", version = "0.3"}
iml-service-queue = {path = "../iml-service-queue", version = "0.3"}
iml-tracing = {version = "0.2", path = "../../iml-tracing"}
iml-wire-types = {path = "../../iml-wire-types", version = "0.3"}
influx_db_client = {version = "0.4", default-features = false, features = ["rustls-tls"]}
lustre_collector = "0.2.13"
thiserror = "1.0"
tokio = {version = "0.2", features = ["macros", "rt-threaded"]}
tracing = "0.1"
url = "2.1.1"
