[package]
name = "stratagem-runner"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
build = "build.rs"

[dependencies]

[lib]
name="llapi"
path = "src/lib.rs"


[[bin]]
name = "stratagem_warning"
path = "src/stratagem_warning.rs"


#[[bin]]
#name = "stratagem_purge"
#path = "src/stratagem_purge.rs"


[build-dependencies]
bindgen = "0.43.1"
