[package]
name = "stratagem-runner"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
liblustreapi = { path = "../liblustreapi", version = "0.1.0" }
csv = "1"
serde = "1"
serde_derive = "1"
libc = "0.2.50"

[[bin]]
name = "stratagem_warning"
path = "src/stratagem_warning.rs"

[[bin]]
name = "stratagem_purge"
path = "src/stratagem_purge.rs"

