[package]
name = "stratagem-runner"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
liblustreapi = { path = "../liblustreapi", version = "0.1.0" }
csv = "1"
serde = { version = "1", features = ["derive"] }
libc = "0.2.50"
log = "0.4.6"
env_logger = "0.6.1"

[[bin]]
name = "stratagem_warning"
path = "src/stratagem_warning.rs"

[[bin]]
name = "stratagem_purge"
path = "src/stratagem_purge.rs"

