language: python
python: '2.7'
sudo: required
services:
  - docker
  - postgresql
addons:
  apt:
    update: true
  postgresql: "9.2"
  apt:
    packages:
      - postgresql-server-dev-9.2
jobs:
  include:
  - stage: test
    env: Type='unit tests'
    install:
      - pip install -r requirements.txt
    before_script:
      - psql -c "CREATE USER chroma;" -U postgres
      - psql -c "ALTER USER chroma CREATEDB;" -U postgres
      - psql -c "CREATE DATABASE chroma OWNER chroma;" -U postgres
    script:
      - export IML_DISABLE_THREADS=1
      - echo "CRYPTO_FOLDER='./'" > local_settings.py
      - python manage.py test tests/unit/
  - stage: cd
    git:
      depth: 999999
    env: Type='Continuous Deployment'
    script:
      - set |grep TRAVIS
      - include/travis/copr-deploy.sh prepare
      - ./travis_wait "./include/travis/run_in_centos7_docker.sh include/travis/copr-deploy.sh build_srpm"
  - stage: test
    env: Type='behave tests'
    install:
      - pip install -r requirements.txt
    before_script:
      - psql -c "CREATE USER chroma;" -U postgres
      - psql -c "ALTER USER chroma CREATEDB;" -U postgres
      - psql -c "CREATE DATABASE chroma OWNER chroma;" -U postgres
    script:
      - export IML_DISABLE_THREADS=1
      - behave --format plain tests/feature/cli/features
  - stage: test
    env: Type='service tests'
    script:
      - docker run -dit --privileged --name systemd --mount type=bind,source="$(pwd)",target=/integrated-manager-for-lustre  -v /sys/fs/cgroup:/sys/fs/cgroup:ro centos/systemd
      - docker exec -i systemd bash -c "./integrated-manager-for-lustre/tests/framework/services/runner.sh"
stages:
  - test
  - name: cd
    if: branch = master AND type = push AND fork = false