language: python
python: '2.7'
sudo: required
services:
  - docker
  - postgresql
addons:
  apt:
    update: true
  postgresql: "9.2"
  apt:
    packages:
      - postgresql-server-dev-9.2
jobs:
  include:
  - stage: test
    name: "Unit Tests"
    install:
      - pip install -r requirements.txt
      - pip install -r requirements.test
    before_script:
      - psql -c "CREATE USER chroma;" -U postgres
      - psql -c "ALTER USER chroma CREATEDB;" -U postgres
      - psql -c "CREATE DATABASE chroma OWNER chroma;" -U postgres
    script:
      - export IML_DISABLE_THREADS=1
      - echo "CRYPTO_FOLDER='./'" > local_settings.py
      - echo -e "/^DEBUG =/s/= .*$/= True/\nwq" | ed settings.py 2>/dev/null
      - python manage.py test tests/unit/
  - stage: cd
    git:
      depth: 999999
    name: "Continuous Deployment (Copr)"
    script:
      - include/travis/copr-deploy.sh prepare
      - ./travis_wait "./include/travis/run_in_centos7_docker.sh include/travis/copr-deploy.sh build_srpm"
  - stage: cd
    git:
      depth: 999999
    name: "Continuous Deployment (Docker)"
    script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --rm -t imlteam/manager-service-base -f base.dockerfile .
      - docker push imlteam/manager-service-base
      - docker build --rm -t imlteam/manager-nginx -f nginx.dockerfile .
      - docker push imlteam/manager-nginx
      - docker-compose build
      - docker-compose push
  - stage: test
    name: "Behave tests"
    install:
      - pip install -r requirements.txt
      - pip install -r requirements.test
    before_script:
      - psql -c "CREATE USER chroma;" -U postgres
      - psql -c "ALTER USER chroma CREATEDB;" -U postgres
      - psql -c "CREATE DATABASE chroma OWNER chroma;" -U postgres
    script:
      - export IML_DISABLE_THREADS=1
      - behave --format plain tests/feature/cli/features
  - stage: test
    name: "Service tests"
    script:
      - docker run -dit --privileged --name systemd --mount type=bind,source="$(pwd)",target=/integrated-manager-for-lustre  -v /sys/fs/cgroup:/sys/fs/cgroup:ro centos/systemd
      - docker exec -i systemd bash -c "./integrated-manager-for-lustre/tests/framework/services/runner.sh"
stages:
  - test
  - name: cd
    if: branch = master AND type = push AND fork = false