language: python
python: "2.7"
sudo: required
services:
  - docker
  - postgresql
jobs:
  include:
    - stage: test
      name: "Service tests"
      script:
        - docker run -dit --privileged --name systemd --mount type=bind,source="$(pwd)",target=/integrated-manager-for-lustre  -v /sys/fs/cgroup:/sys/fs/cgroup:ro centos/systemd
        - docker exec -i systemd yum -y install make sed systemd-python
        - docker exec -i systemd make -C ./integrated-manager-for-lustre/ substs
        - docker exec -i systemd bash -c "./integrated-manager-for-lustre/tests/framework/services/runner.sh"
stages:
  - test
