trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

jobs:
  # Check formatting
  - template: ci/azure-rustfmt.yml
    parameters:
      name: rustfmt

  # Check linting
  - template: ci/azure-clippy.yml
    parameters:
      name: clippy
      displayName: Lint Rust IML

  # Test top level crate
  - template: ci/azure-test-stable.yml
    parameters:
      name: test_iml
      displayName: Test IML

    # Test top level crate
  - template: ci/azure-test-coverage.yml
    parameters:
      name: iml_coverage
      displayName: Collect Rust IML Coverage

  # Check building rpm works
  - template: ci/azure-build-check.yml
    parameters:
      name: test_rpm_build
      displayName: Test rpm building
      spec: rust-iml.spec

  # Continuous Release to Devel Copr
  - template: ci/azure-release.yml
    parameters:
      name: copr_devel_push
      displayName: Copr Devel Push
      project: manager-for-lustre-devel
      package: rust-iml
      spec: rust-iml.spec
      release: false
      branchref: refs/heads/master

  # Release to production Copr
  - template: ci/azure-release.yml
    parameters:
      name: copr_push
      displayName: Copr Push
      project: manager-for-lustre
      package: rust-iml
      spec: rust-iml.spec
      release: true
      branchref: refs/tags/

  # Check formatting
  - template: ci/azure-rustfmt.yml
    parameters:
      name: rustfmt_wasm
      crate: iml-wasm-components

  # Check linting
  - template: ci/azure-clippy.yml
    parameters:
      name: clippy_wasm
      displayName: Lint Wasm Components
      crate: iml-wasm-components

  # Test wasm-components
  - template: ci/azure-test-stable.yml
    parameters:
      name: test_wasm_components
      displayName: Test Wasm components
      crate: iml-wasm-components

  # Check building wasm-components rpm works
  - template: ci/azure-build-check.yml
    parameters:
      name: test_wasm_rpm_build
      displayName: Test wasm rpm building
      spec: iml-wasm-components.spec
      crate: iml-wasm-components

  # Wasm-Components Continuous Release to Devel Copr
  - template: ci/azure-release.yml
    parameters:
      name: wasm_components_copr_push
      displayName: Wasm Components Copr Push
      project: manager-for-lustre-devel
      package: iml-wasm-components
      spec: iml-wasm-components.spec
      crate: iml-wasm-components
      release: false
      branchref: refs/heads/master

  # Wasm-Components Continuous Release to Prod Copr
  - template: ci/azure-release.yml
    parameters:
      name: wasm_components_copr_devel_push
      displayName: Wasm Components Copr Devel Push
      project: manager-for-lustre
      package: iml-wasm-components
      spec: iml-wasm-components.spec
      crate: iml-wasm-components
      release: true
      branchref: refs/tags/
