version: "3.7"
services:
  postgres:
    image: "postgres:9.2.23"
    hostname: "postgres"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chroma
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'postgres' -U 'chroma' -c '\\q'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  rabbit:
    image: "rabbitmq:3.6"
    hostname: "rabbit"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=chroma
      - RABBITMQ_DEFAULT_PASS=chroma123
      - RABBITMQ_DEFAULT_VHOST=chromavhost
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      timeout: 5s
      interval: 5s
      retries: 5
      start_period: 10s
    volumes:
      - /etc/rabbitmq/
      - /var/lib/rabbitmq/
  nginx:
    image: "imlteam/manager-nginx"
    restart: "on-failure"
    hostname: "nginx"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    environment:
      - HTTPS_FRONTEND_PORT=7443
      - SSL_PATH=/var/lib/chroma
      - VIEW_SERVER_PROXY_PASS=http://view-server:8889
      - HTTP_API_PROXY_PASS=http://gunicorn:8001
      - REALTIME_PROXY_PASS=http://realtime:8888
      - HTTP_AGENT_PROXY_PASS=http://http-agent:8002
      - DEVICE_AGGREGATOR_PORT=8008
      - REPO_PATH=/var/lib/chroma/repo
      - SRCMAP_REVERSE_PROXY_PASS=http://srcmap-reverse:8082
      - DEVICE_AGGREGATOR_PROXY_PASS=http://device-aggregator:8083
      - UPDATE_HANDLER_PROXY_PASS=http://update-handler:8080
    volumes:
      - "manager-config:/var/lib/chroma"
      - "static-config1:/usr/lib/iml-manager"
      - "static-config2:/usr/lib/node_modules/@iml"
    ports:
      - "7443:7443"
  update-handler:
    image: "imlteam/iml-update-check"
    restart: on-failure
    hostname: "update-handler"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - "IML_CA_PATH=/var/lib/chroma/authority.crt"
  realtime:
    image: "imlteam/realtime"
    restart: "on-failure"
    hostname: "realtime"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    environment:
      - REALTIME_PORT=8888
      - SERVER_HTTP_URL=https://nginx:7443/
      - LOG_PATH=.
  srcmap-reverse:
    image: "imlteam/srcmap-reverse"
    restart: "on-failure"
    hostname: "srcmap-reverse"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    volumes:
      - static-config1:/usr/lib/iml-manager/
    environment:
      - NODE_ENV=production
      - SOURCE_MAP_PATH=/usr/lib/iml-manager/iml-gui/main.*.js.map
      - SRCMAP_REVERSE_PORT=8082
  view-server:
    image: "imlteam/view-server"
    restart: "on-failure"
    hostname: "view-server"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    volumes:
      - "manager-config:/var/lib/chroma"
      - "static-config1:/usr/lib/iml-manager"
      - "static-config2:/usr/lib/node_modules/@iml"
    depends_on:
      - nginx
  device-aggregator:
    image: "imlteam/device-aggregator"
    hostname: "device-aggregator"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    restart: "on-failure"
    environment:
      - AGGREGATOR_PORT=8083
  corosync:
    image: "imlteam/manager-corosync"
    restart: on-failure
    hostname: "corosync"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - HTTPS_FRONTEND_PORT=7443
      - DB_HOST=postgres
      - DB_PORT=5432
      - AMQP_BROKER_HOST=rabbit
      - SERVER_FQDN=nginx
  gunicorn:
    image: "imlteam/manager-gunicorn"
    restart: on-failure
    hostname: "gunicorn"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    environment:
      - USE_CONSOLE=1
      - PROXY_HOST=gunicorn
      - HTTPS_FRONTEND_PORT=7443
      - DB_HOST=postgres
      - DB_PORT=5432
      - AMQP_BROKER_HOST=rabbit
      - SERVER_FQDN=nginx
  http-agent:
    image: "imlteam/manager-http-agent"
    restart: on-failure
    volumes:
      - "manager-config:/var/lib/chroma"
    hostname: "http-agent"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    environment:
      - HTTPS_FRONTEND_PORT=7443
      - DB_HOST=postgres
      - DB_PORT=5432
      - AMQP_BROKER_HOST=rabbit
      - SERVER_FQDN=nginx
  job-scheduler:
    image: "imlteam/manager-job-scheduler"
    restart: on-failure
    hostname: "job-scheduler"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - HTTPS_FRONTEND_PORT=7443
      - DB_HOST=postgres
      - DB_PORT=5432
      - AMQP_BROKER_HOST=rabbit
      - SERVER_FQDN=nginx
  lustre-audit:
    image: "imlteam/manager-lustre-audit"
    restart: on-failure
    hostname: "lustre-audit"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - HTTPS_FRONTEND_PORT=7443
      - DB_HOST=postgres
      - DB_PORT=5432
      - AMQP_BROKER_HOST=rabbit
      - SERVER_FQDN=nginx
  plugin-runner:
    image: "imlteam/manager-plugin-runner"
    restart: on-failure
    hostname: "plugin-runner"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - HTTPS_FRONTEND_PORT=7443
      - DB_HOST=postgres
      - DB_PORT=5432
      - AMQP_BROKER_HOST=rabbit
      - SERVER_FQDN=nginx
      - DEVICE_AGGREGATOR_URL=http://device-aggregator:8083
      - LOG_PATH=.
  power-control:
    image: "imlteam/manager-power-control"
    restart: on-failure
    hostname: "power-control"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - HTTPS_FRONTEND_PORT=7443
      - DB_HOST=postgres
      - DB_PORT=5432
      - AMQP_BROKER_HOST=rabbit
      - SERVER_FQDN=nginx
  stats:
    image: "imlteam/manager-stats"
    restart: on-failure
    hostname: "stats"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - HTTPS_FRONTEND_PORT=7443
      - DB_HOST=postgres
      - DB_PORT=5432
      - AMQP_BROKER_HOST=rabbit
      - SERVER_FQDN=nginx
  syslog:
    image: "imlteam/manager-syslog"
    restart: on-failure
    hostname: "syslog"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - HTTPS_FRONTEND_PORT=7443
      - DB_HOST=postgres
      - DB_PORT=5432
      - AMQP_BROKER_HOST=rabbit
      - SERVER_FQDN=nginx
      - LOG_PATH=.
  setup:
    image: "imlteam/manager-setup"
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - "manager-config:/var/lib/chroma"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    environment:
      - SERVER_FQDN=nginx
      - HTTPS_FRONTEND_PORT=7443
      - DB_HOST=postgres
      - DB_PORT=5432
      - AMQP_BROKER_HOST=rabbit
    depends_on:
      - postgres
      - rabbit
volumes:
  ? manager-config
  ? db-data
  ? static-config1
  ? static-config2
