[package]
name = "iml-rabbit"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
iml-manager-env = { path = "../iml-manager-env", version = "0.2.0" }
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
lapin = "0.34.0"
serde_json = "1"
tracing = "0.1"
warp = { version = "0.2", optional = true }

[dev-dependencies]
tokio = { version = "0.2", features = ["macros"] }

[features]
warp-filters = ["warp"]