[package]
name = "iml-rabbit"
version = "0.3.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
deadpool-lapin = { git = "https://github.com/bikeshedder/deadpool", default-features = false }
futures = "0.3"
iml-manager-env = { path = "../iml-manager-env", version = "0.3" }
iml-wire-types = { path = "../iml-wire-types", version = "0.3" }
thiserror = "1.0"
lapin = "1.1"
serde_json = "1"
tokio-amqp = "0.1"
tracing = "0.1"
warp = { version = "0.2", optional = true }

[dev-dependencies]
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
warp = "0.2"

[features]
warp-filters = ["warp"]