[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-postoffice"
version = "0.4.0"

[dependencies]
futures = "0.3"
iml-rabbit = {path = "../../iml-rabbit", version = "0.4"}
iml-service-queue = {path = "../iml-service-queue", version = "0.4"}
iml-tracing = {version = "0.3", path = "../../iml-tracing"}
iml-wire-types = {path = "../../iml-wire-types", version = "0.4"}
tokio = {version = "0.2", features = ["rt-threaded"]}
tracing = "0.1"
