[package]
name = "futures-failure"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
license = "MIT"
edition = "2018"

[dependencies]
futures = "0.1"
failure = "0.1.5"

[dev-dependencies]
pretty_assertions = "0.6.1"

