[package]
name = "iml-agent"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
description = "Core library for Integrated Manager for Lustre Agent"
license = "MIT"
repository = "https://github.com/whamcloud/integrated-manager-for-lustre/tree/master/iml-agent"

[dependencies]
bytes = "0.5"
byte-unit = "=2.1"
chrono = "0.4"
dns-lookup = "1"
elementtree = "0.5"
exitcode = "1.1"
futures = "0.3"
lazy_static = "1.4.0"
termion = "1"
spinners = "1.0.0"
libc = "0.2"
prettytable-rs = "0.8"
reqwest = { git = "https://github.com/seanmonstar/reqwest", features = ["default-tls", "tls", "json", "stream"] }
http = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.2"
tokio = { version = "0.2.4", features = ["process"] }
tracing = "0.1"
tracing-subscriber = "0.1"
native-tls = "0.2"
url = "2.1"
v_hist = "0.1.1"
uuid = { version = "0.7", features = ["v4"] }
parking_lot = "0.9"
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
liblustreapi = { path = "../liblustreapi", version = "0.1" }
iml-fs = { path = "../iml-fs", version = "0.1.0" }
iml-util = { path = "../iml-util", version = "0.1.0" }

[dependencies.regex]
version = "1.3"
default-features = false
features = ["std"]

[dev-dependencies]
mockito = "0.22.0"
pretty_assertions = "0.6.1"
insta = "0.12"

[[bin]]
name = "iml-agent-daemon"
path = "src/main.rs"

[[bin]]
name = "iml-agent"
path = "src/cli.rs"
