[package]
name = "iml-job-scheduler-rpc"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
iml-rabbit = { path = "../iml-rabbit", version = "0.1.0" }
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["process"] }
tracing = "0.1"
uuid = { version = "0.8", features = ["v4"] }