[package]
authors = ["IML Team <iml@whamcloud.com>"]
description = "Shared types for the IML project"
edition = "2018"
license = "MIT"
name = "iml-wire-types"
version = "0.3.0"

[dependencies]
bytes = {version = "0.5", optional = true}
chrono = {version = "0.4", features = ["wasmbind", "serde"]}
humantime = "2.0"
im = {version = "15.0", features = ["serde"]}
iml-change = {path = "../iml-change", version = "0.1", optional = true}
juniper = {git = "https://github.com/graphql-rust/juniper", optional = true}
lazy_static = "1.4.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
serde_repr = "0.1"
sqlx = {git = "https://github.com/jgrund/sqlx", branch = "support-offline-workspaces", default-features = false, features = ["json", "macros", "offline", "postgres", "runtime-tokio", "time", "chrono"], optional = true}
structopt = {version = "0.3", optional = true}
thiserror = {version = "1.0", optional = true}
wbem-client = {path = "../wbem-client", version = "0.1", optional = true}

[dependencies.regex]
default-features = false
features = ["std", "unicode-perl"]
version = "1.3"

[features]
cli = ["structopt"]
graphql = ["juniper"]
postgres-interop = ["bytes", "sqlx"]
wbem-interop = ["wbem-client", "thiserror", "iml-change"]
