[package]
name = "iml-wire-types"
description = "Shared types for the IML project"
license = "MIT"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
tokio-postgres = { version = "0.5", optional = true }
postgres-types = { version = "0.1.1", optional = true }
bytes = { version = "0.5", optional = true }
im = { version = "14.3", features = ["serde"] }

[features]
postgres-interop = ["tokio-postgres", "postgres-types", "bytes"]