[package]
authors = ["EMF Team <emf@whamcloud.com>"]
edition = "2018"
name = "emf-corosync"
version = "0.4.0"

[dependencies]
emf-change = {path = "../../emf-change", version = "0.1"}
emf-manager-env = {path = "../../emf-manager-env", version = "0.4"}
emf-postgres = {path = "../../emf-postgres", version = "0.4"}
emf-service-queue = {path = "../emf-service-queue", version = "0.4"}
emf-tracing = {version = "0.4", path = "../../emf-tracing"}
emf-wire-types = {path = "../../emf-wire-types", version = "0.4", features = ["postgres-interop"]}
futures = "0.3"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
sqlx = {version = "0.5", features = ["json", "offline", "postgres", "runtime-tokio-rustls", "chrono"]}
thiserror = "1.0"
tokio = {version = "1", features = ["macros", "rt-multi-thread", "sync"]}

[dev-dependencies]
emf-postgres = {path = "../../emf-postgres", version = "0.4", features = ["test"]}
tokio-test = "0.4"
