[package]
authors = ["EMF Team <emf@whamcloud.com>"]
edition = "2018"
name = "emf-warp-drive"
version = "0.4.0"

[dependencies]
emf-manager-env = {path = "../emf-manager-env", version = "0.4"}
emf-postgres = {path = "../emf-postgres", version = "0.4"}
emf-tracing = {version = "0.4", path = "../emf-tracing"}
emf-wire-types = {path = "../emf-wire-types", version = "0.4", features = ["postgres-interop"]}
futures = "0.3"
im = {version = "15.0", features = ["serde"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
sqlx = {version = "0.5", features = ["json", "offline", "postgres", "runtime-tokio-rustls", "chrono"]}
thiserror = "1"
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
tokio-runtime-shutdown = {path = "../tokio-runtime-shutdown", version = "0.4"}
tracing = "0.1"
uuid = {version = "0.8", features = ["v4"]}
warp = "0.3"
