[package]
name = "iml-stratagem"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
seed = "=0.3.7"
serde = { version = "1", features = ['derive'] }
serde_json = "1.0"
iml-grafana-chart = { path = "../iml-grafana-chart", version = "0.1" }
bootstrap-components = { path = "../bootstrap-components", version = "0.1" }