[package]
name = "iml-stratagem"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
seed = "=0.3.7"
iml-grafana-chart = { path = "../iml-grafana-chart", version = "0.1" }