[package]
name = "iml-fs"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["blocking", "fs", "io-util", "stream"] }
tokio-util = { version = "0.2", features = ["codec"] }
tempfile = "3.1"
bytes = "0.5"

[dev-dependencies]
pretty_assertions = "0.6"
tempdir = "0.3"
tokio = { version = "0.2", features = ["macros"] }
