[package]
name = "iml-fs"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = "0.2.4"
tokio-util = "0.2"
tempfile = "3.1"
bytes = "0.5"

[dev-dependencies]
pretty_assertions = "0.6"
tempdir = "0.3"