[package]
name = "iml-fs"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.19"
tokio = "0.2.0-alpha.6"
tempfile = "3.1"
tokio-executor = "0.2.0-alpha.6"
bytes = "0.4"

[dev-dependencies]
pretty_assertions = "0.6"
tempdir = "0.3"