[package]
name = "iml-ntp"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
iml-orm = { path = "../../iml-orm", version = "0.2.0", features = ["postgres-interop"] }
iml-rabbit = { path = "../../iml-rabbit", version = "0.2.0" }
iml-service-queue = { path = "../iml-service-queue", version = "0.2.0" }
iml-wire-types = { path = "../../iml-wire-types", version = "0.2" }
tokio = { version = "0.2", features = [ "rt-threaded", "blocking" ] }
tracing = "0.1"
tracing-subscriber = "0.2"
