[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-state-machine"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
futures = "0.3"
iml-action-client = {path = "../iml-action-client", version = "0.1"}
iml-postgres = {path = "../iml-postgres", version = "0.4"}
iml-tracing = {path = "../iml-tracing", version = "0.3"}
iml-wire-types = {path = "../iml-wire-types", version = "0.4", features = ["postgres-interop"]}
petgraph = "0.5"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
thiserror = "1.0"
tokio = {version = "0.3", features = ["full"]}
uuid = {version = "0.8", features = ["v4"]}
