version: "3.7"
x-deploy: &default-deploy
  restart_policy:
    condition: any
    delay: 5s
    window: 5s
services:
  postgres:
    image: "postgres:9.6.17-alpine"
    hostname: "postgres"
    deploy:
      <<: *default-deploy
      endpoint_mode: dnsrr
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=chroma
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "psql -h 'postgres' -U 'chroma' -c '\\q'"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
  influxdb:
    image: "imlteam/influxdb:6.2.0-dev"
    build:
      context: ../
      dockerfile: ./docker/influxdb.dockerfile
    hostname: "influxdb"
    deploy: *default-deploy
    volumes:
      - influxdb:/var/lib/influxdb/
      - "manager-config:/var/lib/chroma"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail influxdb:8086/ping?wait_for_leader=10s"]
      interval: 5s
      timeout: 15s
      retries: 5
      start_period: 60s
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_BIND_ADDRESS=influxdb:8088
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_HTTP_BIND_ADDRESS=influxdb:8086
      - INFLUXDB_HTTP_LOG_ENABLED=false
  grafana:
    image: "imlteam/grafana:6.2.0-dev"
    build:
      context: ../
      dockerfile: ./docker/grafana.dockerfile
    hostname: "grafana"
    deploy: *default-deploy
    environment:
      - GF_SERVER_DOMAIN=grafana
      - GF_SERVER_HTTP_PORT=3000
      - GF_SERVER_PROTOCOL=http
      - "GF_DATABASE_HOST=postgres:5432"
    volumes:
      - "manager-config:/var/lib/chroma"
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000
  rabbit:
    image: "rabbitmq:3.6-management-alpine"
    hostname: "rabbit"
    deploy:
      <<: *default-deploy
      endpoint_mode: dnsrr
    environment:
      - RABBITMQ_DEFAULT_USER=chroma
      - RABBITMQ_DEFAULT_PASS=chroma123
      - RABBITMQ_DEFAULT_VHOST=chromavhost
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit heartbeat 0
      - RABBITMQ_ERLANG_COOKIE='lustre-secret'
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      timeout: 5s
      interval: 5s
      retries: 5
      start_period: 10s
  nginx:
    image: "imlteam/manager-nginx:6.2.0-dev"
    build:
      context: ../
      dockerfile: ./docker/nginx.dockerfile
    hostname: "nginx"
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
      - "mailbox:/var/spool/iml/mailbox"
      - "static-config1:/usr/lib/iml-manager"
      - "static-config2:/usr/lib/node_modules/@iml"
    ports:
      - "7443:7443"
  update-handler:
    image: "imlteam/iml-update-check:5.1"
    hostname: "update-handler"
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - "IML_CA_PATH=/var/lib/chroma/authority.crt"
  device:
    image: "imlteam/device:6.2.0-dev"
    hostname: "device"
    build:
      context: ../
      dockerfile: ./docker/iml-device.dockerfile
    deploy: *default-deploy
    environment:
      - DEVICE_AGGREGATOR_PORT=8008
      - PROXY_HOST=device
      - RUST_LOG=info
    volumes:
      - "manager-config:/var/lib/chroma"
  ntp:
    image: "imlteam/ntp:6.2.0-dev"
    hostname: "iml-ntp"
    build:
      context: ../
      dockerfile: ./docker/iml-ntp.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - RUST_LOG=info
  sfa:
    image: "imlteam/sfa:6.2.0-dev"
    hostname: "iml-sfa"
    build:
      context: ../
      dockerfile: ./docker/iml-sfa.dockerfile
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - RUST_LOG=info
      - SFA_ENDPOINTS_1
  corosync:
    image: "imlteam/manager-corosync:6.2.0-dev"
    hostname: "corosync"
    build:
      context: .
      dockerfile: ./corosync.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
  gunicorn:
    image: "imlteam/manager-gunicorn:6.2.0-dev"
    hostname: "gunicorn"
    build:
      context: .
      dockerfile: ./gunicorn.dockerfile
    deploy: *default-deploy
    environment:
      - USE_CONSOLE=1
      - PROXY_HOST=gunicorn
    volumes:
      - "manager-config:/var/lib/chroma"
  http-agent:
    image: "imlteam/manager-http-agent:6.2.0-dev"
    volumes:
      - "manager-config:/var/lib/chroma"
    hostname: "http-agent"
    build:
      context: .
      dockerfile: ./http-agent.dockerfile
    deploy: *default-deploy
    environment:
      - PROXY_HOST=http-agent
  iml-agent-comms:
    image: "imlteam/iml-agent-comms:6.2.0-dev"
    volumes:
      - "manager-config:/var/lib/chroma"
    hostname: "iml-agent-comms"
    build:
      context: ../
      dockerfile: ./docker/iml-agent-comms.dockerfile
    deploy: *default-deploy
    environment:
      - HTTP_AGENT2_PORT=8003
      - PROXY_HOST=iml-agent-comms
      - RUST_LOG=info
  job-scheduler:
    image: "imlteam/manager-job-scheduler:6.2.0-dev"
    hostname: "job-scheduler"
    build:
      context: .
      dockerfile: ./job-scheduler.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
      - "mailbox:/var/spool/iml/mailbox"
      - "/root/.ssh:/root/.ssh"
    environment:
      - DEVICE_AGGREGATOR_URL=http://device:8008
      - PROXY_HOST=iml-action-runner
      - INFLUXDB_SERVER_FQDN=influxdb
  lustre-audit:
    image: "imlteam/manager-lustre-audit:6.2.0-dev"
    hostname: "lustre-audit"
    build:
      context: .
      dockerfile: ./lustre-audit.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
  plugin-runner:
    image: "imlteam/manager-plugin-runner:6.2.0-dev"
    hostname: "plugin-runner"
    build:
      context: .
      dockerfile: ./plugin-runner.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - DEVICE_AGGREGATOR_URL=http://device:8008
  power-control:
    image: "imlteam/manager-power-control:6.2.0-dev"
    hostname: "power-control"
    build:
      context: .
      dockerfile: ./power-control.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
  syslog:
    image: "imlteam/manager-syslog:6.2.0-dev"
    hostname: "syslog"
    build:
      context: .
      dockerfile: ./syslog.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
  iml-warp-drive:
    image: "imlteam/iml-warp-drive:6.2.0-dev"
    hostname: "iml-warp-drive"
    build:
      context: ../
      dockerfile: ./docker/iml-warp-drive.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - PROXY_HOST=iml-warp-drive
      - RUST_LOG=info
  iml-action-runner:
    image: "imlteam/iml-action-runner:6.2.0-dev"
    hostname: "iml-action-runner"
    build:
      context: ../
      dockerfile: ./docker/iml-action-runner.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - PROXY_HOST=iml-action-runner
      - ACTION_RUNNER_PORT=8009
      - RUST_LOG=info
  iml-api:
    image: "imlteam/iml-api:6.2.0-dev"
    hostname: "iml-api"
    build:
      context: ../
      dockerfile: ./docker/iml-api.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - PROXY_HOST=iml-api
      - RUST_LOG=info
      - BRANDING
      - USE_STRATAGEM
      - EXA_VERSION
      - SFA_ENDPOINTS_1
  iml-manager-cli:
    image: "imlteam/iml-manager-cli:6.2.0-dev"
    stdin_open: true
    tty: true
    build:
      context: ../
      dockerfile: ./docker/iml-manager-cli.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - SERVER_HTTP_URL=gunicorn
  iml-ostpool:
    image: "imlteam/iml-ostpool:6.2.0-dev"
    hostname: "iml-ostpool"
    build:
      context: ../
      dockerfile: ./docker/iml-ostpool.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - RUST_LOG=info
  iml-mailbox:
    image: "imlteam/iml-mailbox:6.2.0-dev"
    hostname: "iml-mailbox"
    build:
      context: ../
      dockerfile: ./docker/iml-mailbox.dockerfile
    deploy: *default-deploy
    volumes:
      - "mailbox:/var/spool/iml/mailbox"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "mailbox_run:/run"
      - "manager-config:/var/lib/chroma"
  iml-stats:
    image: "imlteam/iml-stats:6.2.0-dev"
    hostname: "iml-stats"
    build:
      context: ../
      dockerfile: ./docker/iml-stats.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - RUST_LOG=info
      - PROXY_HOST=influxdb
  iml-postoffice:
    image: "imlteam/iml-postoffice:6.2.0-dev"
    hostname: "iml-postoffice"
    build:
      context: ../
      dockerfile: ./docker/iml-postoffice.dockerfile
    deploy: *default-deploy
    volumes:
      - "manager-config:/var/lib/chroma"
    environment:
      - PROXY_HOST=iml-postoffice
  iml-timer:
    image: "imlteam/iml-timer:6.2.0-dev"
    hostname: "iml-timer"
    build:
      context: ../
      dockerfile: ./docker/iml-timer.dockerfile
    deploy: *default-deploy
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "timer_run:/run"
      - "timer_systemd:/var/lib/systemd"
      - "timer_system:/etc/systemd/system"
      - "manager-config:/var/lib/chroma"
  setup:
    image: "imlteam/manager-setup:6.2.0-dev"
    command: ["tail", "-f", "/dev/null"]
    build:
      context: .
      dockerfile: ./setup.dockerfile
    volumes:
      - "manager-config:/var/lib/chroma"
      - "/etc/iml-docker/setup:/var/lib/chroma-setup"
    secrets:
      - iml_pw
    environment:
      - BRANDING
      - USE_STRATAGEM
      - EXA_VERSION
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 5s
volumes:
  manager-config:
  db-data:
  influxdb:
  grafana-storage:
  static-config1:
  static-config2:
  mailbox:
  mailbox_run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  timer_run:
    driver_opts:
      type: tmpfs
      device: tmpfs
  timer_system:
  timer_systemd:
secrets:
  iml_pw:
    external: true
