version: "3.7"
services:
  postgres:
    restart: on-failure
  influxdb:
    restart: on-failure
  grafana:
    restart: on-failure
  rabbit:
    restart: on-failure
  nginx:
    restart: on-failure
  device:
    restart: on-failure
  ntp:
    restart: on-failure
  corosync:
    restart: on-failure
  gunicorn:
    restart: on-failure
  http-agent:
    restart: on-failure
  emf-agent-comms:
    restart: on-failure
  job-scheduler:
    restart: on-failure
  plugin-runner:
    restart: on-failure
  journal:
    restart: on-failure
  emf-ostpool:
    restart: on-failure
  emf-stats:
    restart: on-failure
  emf-warp-drive:
    restart: on-failure
  setup:
    restart: on-failure
  emf-action-runner:
    restart: on-failure
  emf-api:
    restart: on-failure
  emf-postoffice:
    restart: on-failure
secrets:
  emf_pw:
    file: /tmp/emf_pw
