[package]
name = "zed-enhancer"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
license = "MIT"
edition = "2018"

[dependencies]
tokio = "0.2.0-alpha.6"
tokio-net = { version = "0.2.0-alpha.6", features = ["process"] }
futures-preview = "0.3.0-alpha.19"
derive_more = "0.15.0"
serde_json = "1.0"
device-types = { path = "../device-types", version = "0.1.0" }
libzfs-types = { git = "https://github.com/whamcloud/rust-libzfs.git", version = "0.1.2" }
libzfs = { git = "https://github.com/whamcloud/rust-libzfs.git", version = "0.6.16" }
tracing = "0.1"
tracing-subscriber = "0.1"