[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
license = "MIT"
name = "zed-enhancer"
version = "0.2.0"

[dependencies]
device-types = {path = "../device-types", version = "0.3.0"}
futures = "0.3"
libzfs = "0.6.16"
libzfs-types = "0.1.2"
serde_json = "1.0"
thiserror = "1.0"
tokio = {version = "0.2", default-features = false, features = ["net", "io-util", "process", "macros", "rt-core"]}
tokio-util = {version = "0.3", features = ["codec"]}
tracing = "0.1"
tracing-subscriber = "0.2"
