[package]
name = "iml-manager-cli"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
combine = "=4.0.1"
console = "0.10"
dialoguer = "0.5"
dotenv = "0.15"
futures = "0.3"
hostlist-parser = "0.1.2"
iml-api-utils = { path = "../iml-api-utils", version = "0.1" }
iml-manager-client = { path = "../iml-manager-client", version = "0.1.0" }
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
indicatif = "0.14"
number-formatter = { path = "../number-formatter", version = "0.1" }
prettytable-rs = "0.8"
reqwest = { version = "0.10", features = ["default-tls", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spinners = "1.2.0"
structopt = "0.3"
tokio = { version = "0.2", features = ["macros", "io-std", "io-util"] }
tracing = "0.1"
tracing-subscriber = "0.2"

[[bin]]
name = "iml"
path = "src/main.rs"
