[package]
name = "iml-manager-cli"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
dotenv = "0.14"
futures-preview = "0.3.0-alpha.19"
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
iml-manager-client = { path = "../iml-manager-client", version = "0.1.0" }
prettytable-rs = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spinners = "1.0.0"
structopt = "0.2"
termion = "1"
tokio = "0.2.0-alpha.6"
tracing = "0.1"
tracing-subscriber = "0.1"

[[bin]]
name = "iml"
path = "src/main.rs"