[package]
name = "iml-manager-messaging"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
futures = "0.1.25"
iml-wire-types = { path = "../iml-wire-types", version = "0.1.0" }
iml-rabbit = { path = "../iml-rabbit", version = "0.1.0" }
iml-manager-env = { path = "../iml-manager-env", version = "0.1.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"