[package]
authors = ["IML Team <iml@whamcloud.com>"]
description = "Utilities for working with the IML command API"
edition = "2018"
license = "MIT"
name = "iml-command-utils"
version = "0.3.0"

[dependencies]
console = "0.11"
futures = "0.3"
iml-graphql-queries = {path = "../iml-graphql-queries", version = "0.1"}
iml-manager-client = {path = "../iml-manager-client", version = "0.3"}
iml-wire-types = {version = "0.3", path = "../iml-wire-types"}
indicatif = "0.14"
number-formatter = {path = "../number-formatter", version = "0.1"}
prettytable-rs = "0.8"
reqwest = {version = "0.10", default-features = false, features = ["rustls-tls", "json"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
serde_yaml = "0.8"
spinners = "1.2.0"
structopt = "0.3"
thiserror = "1.0"
tokio = {version = "0.2", features = ["macros", "io-std", "io-util", "fs", "rt-threaded"]}
tracing = "0.1"

[features]
cli = []
