[package]
authors = ["EMF Team <emf@whamcloud.com>"]
description = "An asynchronous Web-Based Enterprise Management (WBEM) client"
edition = "2018"
license = "MIT"
name = "wbem-client"
repository = "https://github.com/whamcloud/exascaler-management-framework/tree/master/wbem-client"
version = "0.2.0"

[dependencies]
async-trait = "0.1"
bytes = "1"
futures = "0.3"
emf-tracing = {version = "0.4", path = "../emf-tracing"}
quick-xml = {version = "0.19", features = ["serialize"]}
reqwest = {version = "0.11", default-features = false, features = ["default-tls"]}
serde = {version = "1", features = ["derive"]}
thiserror = "1.0"

[dev-dependencies]
insta = "1"
