[package]
name = "iml-system-docker-tests"
version = "0.3.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
iml-cmd = { version = "0.3", path = "../iml-cmd" }
iml-system-test-utils = { version = "0.3", path = "../iml-system-test-utils" }
iml-systemd = { version = "0.3", path = "../iml-systemd" }
iml-wire-types = { version = "0.3", path = "../iml-wire-types" }
petgraph = "0.5"
tokio = { version="0.2", features=["macros"] }
tracing = "0.1"
tracing-subscriber = "0.2"
