[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-system-docker-tests"
version = "0.4.0"

[dependencies]
iml-cmd = {version = "0.4", path = "../iml-cmd"}
iml-system-test-utils = {version = "0.4", path = "../iml-system-test-utils"}
iml-systemd = {version = "0.4", path = "../iml-systemd"}
iml-wire-types = {version = "0.4", path = "../iml-wire-types"}
petgraph = "0.5"
tokio = {version = "0.2", features = ["macros", "rt-threaded"]}
tracing = "0.1"
tracing-subscriber = "0.2"
