[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-journal"
version = "0.4.0"

[dependencies]
chrono = "0.4"
futures = "0.3"
iml-manager-env = {path = "../../iml-manager-env", version = "0.4"}
iml-postgres = {path = "../../iml-postgres", version = "0.4"}
iml-rabbit = {path = "../../iml-rabbit", version = "0.4"}
iml-service-queue = {path = "../iml-service-queue", version = "0.4"}
iml-tracing = {version = "0.3", path = "../../iml-tracing"}
iml-wire-types = {path = "../../iml-wire-types", version = "0.4", features = ["postgres-interop"]}
lazy_static = "1.4.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
tokio = {version = "0.2", features = ["macros"]}

[dependencies.regex]
default-features = false
features = ["std"]
version = "1.3"

[dev-dependencies]
insta = "1.0"
