[package]
name = "emf-exa-parser"
version = "0.1.0"
authors = ["EMF Team <emf@whamcloud.com>"]
edition = "2018"

[dev-dependencies]
insta = "1"

[dependencies]
emf-cmd = {path = "../emf-cmd", version = "0.4.0"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
