[package]
name = "iml-orm"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4", features = ["postgres", "r2d2", "chrono"], optional = true }
iml-manager-env = { path = "../iml-manager-env", version = "0.2.0", optional = true }
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
ipnetwork = "0.16"
r2d2 = {version = "0.8", optional = true }
serde = { version = "1", features = ["derive"] }
tokio-diesel = { git = "https://github.com/jgrund/tokio-diesel", branch = "use-block-in-place", optional = true }

[features]
postgres-interop = ["diesel", "iml-manager-env", "r2d2", "tokio-diesel"]
wasm = ["chrono/wasmbind"]