[package]
name = "iml-device"
version = "0.3.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
device-types = "0.1"
diesel = { version = "1.4", default_features = false, features = ["postgres", "r2d2", "chrono", "serde_json"] }
futures = "0.3"
im = { version = "13.0", features = ["serde"] }
iml-manager-env = { path = "../../iml-manager-env", version = "0.3" }
iml-orm = { path = "../../iml-orm", version = "0.3", features = ["postgres-interop"] }
iml-postgres = { path = "../../iml-postgres", version = "0.3" }
iml-rabbit = { path = "../../iml-rabbit", version = "0.3" }
iml-service-queue = { path = "../iml-service-queue", version = "0.3" }
iml-tracing = { version = "0.2", path="../../iml-tracing"}
iml-wire-types = { path = "../../iml-wire-types", version = "0.3", features = ["postgres-interop"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "0.2", features = ["macros"] }
tokio-util = { version = "0.3", features = ["codec"] }
tracing = "0.1"
warp = "0.2"

[dev-dependencies]
insta = "0.16"
