[package]
authors = ["EMF Team <emf@whamcloud.com>"]
build = "build.rs"
edition = "2018"
name = "liblustreapi-types"
version = "0.4.0"

[dependencies]
libc = "0.2.76"

[build-dependencies]
bindgen = "0.49.0"
