[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-sfa"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
futures = "0.3"
iml-manager-env = {version = "0.3", path = "../iml-manager-env"}
iml-orm = {path = "../iml-orm", version = "0.3", features = ["postgres-interop", "wbem-interop"]}
iml-request-retry = {path = "../iml-request-retry", version = "0.3"}
iml-tracing = {version = "0.2", path = "../iml-tracing"}
thiserror = "1.0"
tokio = {version = "0.2", features = ["macros", "time", "rt-threaded"]}
url = "2.1"
wbem-client = {version = "0.1", path = "../wbem-client"}
