[package]
name = "iml-jobber"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
tokio = "0.2.7"
warp = { git = "https://github.com/seanmonstar/warp.git" }
tracing = "0.1"
tracing-subscriber = "0.1"