[package]
name = "liblustreapi"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
liblustreapi-sys = { path = "../liblustreapi-sys", version = "0.1.0"}
libc = "0.2.50"
errno = "0.2.4"
log = "0.4.6"
