[package]
name = "tokio-runtime-shutdown"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
stream-cancel = "0.4.4"
parking_lot = "0.7"
futures = "0.1.26"

[dev-dependencies]
tokio = "0.1.18"