[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "tokio-runtime-shutdown"
version = "0.4.0"

[dependencies]
futures = "0.3"
stream-cancel = "0.5"

[dev-dependencies]
tokio = "0.2"
tokio-test = "0.2"
