[package]
name = "tokio-runtime-shutdown"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
stream-cancel = "0.5.0-alpha.4"
futures-preview = "0.3.0-alpha.19"

[dev-dependencies]
tokio-test = "0.2.0-alpha.6"
tokio = "0.2.0-alpha.6"