[package]
name = "tokio-runtime-shutdown"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
stream-cancel = "0.5"
futures = "0.3"

[dev-dependencies]
tokio-test = "0.2"
tokio = "0.2"