[package]
authors = ["EMF Team <emf@whamcloud.com>"]
edition = "2018"
name = "emf-journal"
version = "0.4.0"

[dependencies]
chrono = "0.4"
futures = "0.3"
emf-manager-env = {path = "../../emf-manager-env", version = "0.4"}
emf-postgres = {path = "../../emf-postgres", version = "0.4"}
emf-rabbit = {path = "../../emf-rabbit", version = "0.4"}
emf-service-queue = {path = "../emf-service-queue", version = "0.4"}
emf-tracing = {version = "0.3", path = "../../emf-tracing"}
emf-wire-types = {path = "../../emf-wire-types", version = "0.4", features = ["postgres-interop"]}
lazy_static = "1.4.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
tokio = {version = "0.2", features = ["macros"]}

[dependencies.regex]
default-features = false
features = ["std"]
version = "1.3"

[dev-dependencies]
insta = "1"
