[package]
name = "device-scanner-zedlets"
version = "0.1.0"
description = "zedlets that update device-scanner-daemon state"
authors = ["IML Team <iml@whamcloud.com>"]
license = "MIT"
edition = "2018"

[[bin]]
name = "history_event-scanner"
path = "src/bin/history_event.rs"

[[bin]]
name = "pool_create-scanner"
path = "src/bin/pool_create.rs"

[[bin]]
name = "pool_destroy-scanner"
path = "src/bin/pool_destroy.rs"

[[bin]]
name = "pool_export-scanner"
path = "src/bin/pool_export.rs"


[[bin]]
name = "pool_import-scanner"
path = "src/bin/pool_import.rs"


[[bin]]
name = "vdev_add-scanner"
path = "src/bin/vdev_add.rs"

[dependencies]
device-types = { path = "../device-types", version = "0.1.0" }
serde_json = "1.0"
