trigger:
  branches:
    - master
  tags:
    exclude:
      - v*r5.0
    include:
      - v*.*.*-*

jobs:
  # Release to production Copr
  - template: template/azure-release.yml
    parameters:
      name: copr_push
      displayName: Copr Push
      project: manager-for-lustre
      package: rust-iml
      spec: rust-iml.spec
      release: true

  # Wasm-Components Continuous Release to Prod Copr
  - template: template/azure-release.yml
    parameters:
      name: wasm_components_copr_push
      displayName: Wasm Components Copr Push
      project: manager-for-lustre
      package: iml-wasm-components
      spec: iml-wasm-components.spec
      crate: iml-wasm-components
      release: true
