trigger:
  branches:
    include:
      - b5.1
    exclude:
      - refs/pulls
  tags:
    include:
      - v*r5.1

jobs:
  # Release to production Copr
  - template: template/azure-release.yml
    parameters:
      name: copr_push
      displayName: Copr Push
      project: manager-for-lustre-5.1
      package: rust-iml
      spec: rust-iml.spec
      release: true
      branchref: refs/tags/v0.1.2rust-r5.1
      image: imlteam/copr-rust:stable

  # Wasm-Components Continuous Release to Prod Copr
  - template: template/azure-release.yml
    parameters:
      name: wasm_components_copr_push
      displayName: Wasm Components Copr Push
      project: manager-for-lustre-5.1
      package: iml-wasm-components
      spec: iml-wasm-components.spec
      crate: iml-wasm-components
      release: true
      branchref: refs/tags/v0.1.2rust-r5.1
      image: imlteam/copr-wasm
