[package]
name = "iml-action-dropdown"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
seed = "=0.3.6"
serde = { version = "1", features = ['derive'] }
serde_json = "1.0"
futures = "0.1"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"]}
web-sys = { version = "0.3", features = ["CustomEvent", "CustomEventInit", "Event", "EventTarget", "Element"]}
js-sys = "0.3"
cfg-if = "0.1"
log = "0.4"
iml-tooltip = { path = "../iml-tooltip", version = "0.1.0" }
iml-sleep = { path = "../iml-sleep", version = "0.1.0" }
iml-wire-types = "0.1.2"
console_log = { version = "0.1", optional = true }


[dev-dependencies]
wasm-bindgen-test = "0.2"
insta = "0.8.1"

[features]
default = ["console_log"]