[workspace]
members = [
    'iml-action-dropdown',
    'iml-alert-indicator',
    'iml-duration-picker',
    'iml-environment',
    'iml-lock-indicator',
    'iml-pie-chart',
    'iml-popover',
    'iml-sleep',
    'iml-tooltip',
    'iml-utils',
    'iml-wasm'
]

[profile.release]
opt-level = "z"
lto = true