[package]
name = "iml-postgres"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
tokio-postgres = "0.5.0-alpha.2"
futures = "0.3"
tracing = "0.1"
iml-manager-env = { path = "../iml-manager-env", version = "0.1.0" }
