[package]
name = "iml-tracing"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = [ "signal", "rt-core" ] }
tracing = "0.1"
tracing-subscriber = "0.2"