[package]
authors = ["EMF Team <emf@whamcloud.com>"]
edition = "2018"
name = "emf-stats"
version = "0.4.0"

[dependencies]
emf-influx = {path = "../../emf-influx", version = "0.2", features = ["with-db-client"]}
emf-manager-env = {path = "../../emf-manager-env", version = "0.4"}
emf-service-queue = {path = "../emf-service-queue", version = "0.4"}
emf-tracing = {version = "0.3", path = "../../emf-tracing"}
emf-wire-types = {path = "../../emf-wire-types", version = "0.4"}
futures = "0.3"
lustre_collector = "0.2.16"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
tokio = {version = "0.2", features = ["macros", "rt-threaded"]}
tracing = "0.1"
url = "2.1.1"
