[package]
authors = ["EMF Team <emf@whamcloud.com>"]
edition = "2018"
name = "emf-tracing"
version = "0.4.0"

[dependencies]
tokio = {version = "1", features = ["signal", "rt"]}
tracing = "0.1"
tracing-subscriber = "0.2"
