apiVersion: 1

datasources:
  - name: "iml-postgres"
  - type: postgres
  - access: proxy
  - user: chroma
  - database: chroma
  - url: http://postgres:5432
  - jsonData: { sslmode: disable }

version: 1
editable: false
