[package]
name = "iml-lock-indicator"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
seed = "=0.4.0"
log = "0.4"
iml-tooltip = { path = "../iml-tooltip", version = "0.1" }
iml-wire-types = "0.1"
bootstrap-components = { path = "../bootstrap-components", version = "0.1" }
iml-utils = { path = "../iml-utils", version = "0.1" }

[lib]
path = "lock-indicator.rs"