[package]
name = "liblustreapi"
version = "0.1.0"
authors = ["Nathaniel Clark <nclark@whamcloud.com>"]
edition = "2018"

[dependencies]
liblustreapi-sys = { path = "../liblustreapi-sys", version = "0.1.0"}
