[package]
name = "iml-wasm"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"


[lib]
crate-type = ["cdylib"]
name = "package"

[dependencies]
seed = "=0.3.7"
serde = { version = "1", features = ['derive'] }
serde_json = "1.0"
futures = "0.1"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"]}
web-sys = { version = "0.3", features = ["CustomEvent", "CustomEventInit", "Event", "EventTarget", "Element"]}
js-sys = "0.3"
cfg-if = "0.1"
log = "0.4"
console_log = { version = "0.1", optional = true }
iml-action-dropdown = { path = "../iml-action-dropdown", version = "0.1" }
iml-tooltip = { path = "../iml-tooltip", version = "0.1" }
iml-utils = { path = "../iml-utils", version = "0.1" }
iml-wire-types = "0.1"
iml-fs = { path = "../iml-fs", version = "0.1" }


# [features]
# default = ["console_log"]