[package]
name = "emf-state-machine"
version = "0.1.0"
authors = ["EMF Team <emf@whamcloud.com>"]
edition = "2018"

[dependencies]
jsonschema-valid = "0.4.0"
lazy_static = "1.4"
serde_json = "1"
serde_yaml = "0.8"
thiserror = "1.0"

[dev-dependencies]
insta = "1"
serde_json = {features = ["preserve_order"]}
