[package]
authors = ["EMF Team <emf@whamcloud.com>"]
edition = "2018"
name = "emf-state-machine"
version = "0.1.0"

[dependencies]
emf-wire-types = {path = "../emf-wire-types", version = "0.4"}
humantime-serde = "1.0"
jsonschema-valid = "0.4.0"
lazy_static = "1.4"
petgraph = {version = "0.5", features = ["serde-1"]}
serde = "1.0"
serde_json = "1"
serde_yaml = "0.8"
thiserror = "1.0"

[dev-dependencies]
insta = "1"
serde_json = {version = "1.0", features = ["preserve_order"]}
