[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-cmd"
version = "0.4.0"

[dependencies]
futures = "0.3"
tokio = {version = "0.2", features = ["process", "rt-threaded"]}
tracing = "0.1"
warp = {version = "0.2", optional = true}

[features]
warp-errs = ["warp"]
