[package]
name = "iml-cmd"
version = "0.2.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = { version = "0.2", features = ["process"] }
tracing = "0.1"
warp = { version = "0.2", optional = true }

[features]
warp-errs = ["warp"]