[package]
authors = ["EMF Team <emf@whamcloud.com>"]
edition = "2018"
name = "emf-service-queue"
version = "0.4.0"

[dependencies]
emf-wire-types = {path = "../../emf-wire-types", version = "0.4"}
futures = "0.3"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
tokio = "1"
tokio-stream = "0.1"
tracing = "0.1"
uuid = {version = "0.8", features = ["v4"]}
warp = "0.3"
