[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-timer"
version = "0.3.0"

[dependencies]
futures = "0.3"
iml-cmd = {path = "../iml-cmd", version = "0.3", features = ["warp-errs"]}
iml-manager-env = {path = "../iml-manager-env", version = "0.3"}
iml-tracing = {version = "0.2", path = "../iml-tracing"}
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
tokio = {version = "0.2", features = ["process", "macros"]}
warp = "0.2"
