[package]
name = "iml-timer"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["process", "macros"] }
warp = "0.2"
tracing = "0.1"
tracing-subscriber = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
iml-manager-env = { path = "../iml-manager-env", version = "0.1.0" }