[package]
name = "iml-action-client"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iml-action-runner = { path = "../iml-services/iml-action-runner", version = "0.2" }
iml-fs = { path = "../iml-fs", version = "0.2" }
iml-manager-env = { path = "../iml-manager-env", version = "0.2" }
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
futures = "0.3"
reqwest = { version = "0.10", features = ["default-tls", "native-tls", "json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
uuid = { version = "0.8", features = ["v4"] }
