[package]
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"
name = "iml-api"
version = "0.4.0"

[dependencies]
casbin = "2.0.2"
chrono = "0.4"
futures = "0.3"
humantime = "2.0"
iml-job-scheduler-rpc = {path = "../iml-job-scheduler-rpc", version = "0.4"}
iml-manager-client = {path = "../iml-manager-client", version = "0.4"}
iml-manager-env = {path = "../iml-manager-env", version = "0.4"}
iml-postgres = {path = "../iml-postgres", version = "0.4"}
iml-rabbit = {path = "../iml-rabbit", version = "0.4", features = ["warp-filters"]}
iml-tracing = {version = "0.3", path = "../iml-tracing"}
iml-wire-types = {path = "../iml-wire-types", version = "0.4", features = ["graphql", "postgres-interop"]}
itertools = "0.9"
juniper = {git = "https://github.com/graphql-rust/juniper"}
lazy_static = "1.4.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
thiserror = "1.0"
tokio = {version = "0.2", features = ["macros", "rt-threaded"]}
tracing = "0.1"
uuid = {version = "0.8", features = ["v4"]}
warp = "0.2"

[dependencies.regex]
default-features = false
features = ["std"]
version = "1.4"
