[package]
name = "iml-api"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
iml-manager-env = { path = "../iml-manager-env", version = "0.1" }
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
tokio = { version = "0.2", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.1"
warp = "0.2"