[package]
authors = ["IML Team <iml@whamcloud.com>"]
description = "Utilities for working with the IML API"
edition = "2018"
license = "MIT"
name = "iml-api-utils"
version = "0.4.0"

[dependencies]
lazy_static = "1.4.0"

[dependencies.regex]
default-features = false
features = ["std", "unicode-perl"]
version = "1.3"
