[package]
authors = ["EMF Team <emf@whamcloud.com>"]
description = "Shared types for the EMF project"
edition = "2018"
license = "MIT"
name = "emf-wire-types"
version = "0.4.0"

[dependencies]
bytes = {version = "1", optional = true}
chrono = {version = "0.4", features = ["wasmbind", "serde"]}
elementtree = {version = "0.5", optional = true}
emf-api-utils = {path = "../emf-api-utils", version = "0.4"}
emf-change = {path = "../emf-change", version = "0.1", optional = true}
humantime = "2.0"
im = {version = "15.0", features = ["serde"]}
ipnetwork = "0.17"
juniper = {version = "0.15", optional = true}
petgraph = {version = "0.5", features = ["serde-1"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
serde_repr = "0.1"
sqlx = {version = "0.5", default-features = false, features = ["json", "macros", "offline", "postgres", "runtime-tokio-rustls", "chrono", "migrate"], optional = true}
structopt = {version = "0.3", optional = true}
thiserror = "1.0"
wbem-client = {path = "../wbem-client", version = "0.2", optional = true}

[features]
cli = ["structopt"]
graphql = ["juniper"]
postgres-interop = ["bytes", "sqlx"]
wbem-interop = ["wbem-client", "emf-change"]
xml = ["elementtree"]
