[package]
name = "iml-systemd"
description = "IML Systemd Library"
license = "MIT"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
iml-cmd = { path = "../iml-cmd", version = "0.1.0" }
iml-wire-types = { path = "../iml-wire-types", version = "0.2" }
serde = { version = "1", features = ['derive'] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["net", "stream", "time"] }
tracing = "0.1"
