[package]
name = "iml-request-retry"
version = "0.1.0"
description = "IML async request retry Library"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
tokio = "0.2.4"
rand = "0.7.2"
tracing = "0.1.10"

[dev-dependencies]
tokio-test = "0.2.0"
http = "0.2"
reqwest = { git = "https://github.com/seanmonstar/reqwest", features = ["json"] }
url = "2.1.0"
rand_xorshift = "0.2.0"
warp = { git = "https://github.com/seanmonstar/warp.git" }
serde = { version = "1", features = ['derive'] }
serde_json = "1.0"

[[example]]
name = "demo-server-client"
path = "examples/demo-server-client.rs"

