name: IML Docker CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check_rpm_build:
    name: Check RPM build (iml-docker)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the iml images
        working-directory: ./docker
        run: |
          make save
          docker image ls

      - name: Build rpm
        uses: ./.github/actions/copr
        env:
          SPEC: iml-docker.spec
          LOCAL_ONLY: true
          SRPM_TASK: iml-docker-srpm
          WORKSPACE: ${{ github.workspace }}
      - name: Archive rpm
        uses: actions/upload-artifact@v1
        with:
          name: rpm
          path: _topdir/RPMS/x86_64
