name: nightly-build
on:
  schedule:
    - cron: "* 0 * * *"
  workflow_dispatch:
defaults:
  run:
    shell: bash -eux {0}
jobs:
  gui_rpm_build:
    name: GUI RPM build
    runs-on: ubuntu-latest
    container:
      image: emfteam/emf-centos7-deps
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build rpm
        run: make RPM_DIST=".$(date '+%s')" emf-gui-rpm

      - name: Archive rpm
        uses: actions/upload-artifact@v2
        with:
          name: gui_rpm
          path: _topdir/RPMS/x86_64
          retention-days: 1
  rust_emf_rpm_build:
    name: Rust EMF RPM build
    runs-on: ubuntu-latest
    container:
      image: emfteam/emf-centos7-deps
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build rpm
        run: make RPM_DIST=".$(date '+%s')" rust-core-rpms

      - name: Archive rpm
        uses: actions/upload-artifact@v2
        with:
          name: rust_rpm
          path: _topdir/RPMS/x86_64
          retention-days: 1
  device_scanner_rpm_build:
    name: Device Scanner RPM build
    runs-on: ubuntu-latest
    container:
      image: emfteam/emf-centos7-deps
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build rpm
        run: make RPM_DIST=".$(date '+%s')" device-scanner-rpms

      - name: Archive rpm
        uses: actions/upload-artifact@v2
        with:
          name: device_scanner_rpm
          path: _topdir/RPMS/x86_64
          retention-days: 1
  sos_plugin_build:
    name: EMF SOS Plugin
    runs-on: ubuntu-latest
    container:
      image: emfteam/emf-centos7-deps
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Build rpm
        run: make RPM_DIST=".$(date '+%s')" sos-rpm

      - name: Archive rpm
        uses: actions/upload-artifact@v2
        with:
          name: sos_rpm
          path: _topdir/RPMS/noarch
          retention-days: 1
  create_emf_repo:
    name: create EMF repo
    runs-on: ubuntu-latest
    needs:
      - device_scanner_rpm_build
      - gui_rpm_build
      - rust_emf_rpm_build
      - sos_plugin_build
    container:
      image: centos:7
    steps:
      - name: Cancel Workflow Action
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Download GUI RPMs
        uses: actions/download-artifact@v1
        with:
          name: gui_rpm
          path: emf_rpms
      - name: Download Rust RPMs
        uses: actions/download-artifact@v1
        with:
          name: rust_rpm
          path: emf_rpms
      - name: Download Device Scanner RPMs
        uses: actions/download-artifact@v1
        with:
          name: device_scanner_rpm
          path: emf_rpms
      - name: Download sos-plugin RPM
        uses: actions/download-artifact@v1
        with:
          name: sos_rpm
          path: emf_rpms
      - run: |
          yum install -y createrepo yum-utils
          createrepo --pretty emf_rpms
          ls -l
      - name: Archive repo
        uses: actions/upload-artifact@v2
        with:
          name: emf_repo
          path: emf_rpms
          retention-days: 1
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            gui_rpm
            rust_rpm
            device_scanner_rpm
            sos_rpm
  trigger_jenkins_build:
    name: Trigger jenkins build
    runs-on: ubuntu-latest
    needs: create_emf_repo
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Trigger build
        uses: ./.github/actions/jenkins-build
        with:
          jenkins-url: "https://build.whamcloud.com/"
          jenkins-user: ${{ secrets.JENKINS_USER }}
          jenkins-token: ${{ secrets.JENKINS_KEY }}
          job-name: "emf-repo"
          branch: master
          sha: ${{ github.sha }}
