name: emf-python
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "00 01 * * *"

jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install --upgrade pip black

      - name: check
        run: black --check ./
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6.17
        env:
          POSTGRES_USER: chroma
          POSTGRES_PASSWORD: chroma
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: "2.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools pipenv
          pipenv install --dev

      - name: Run tests
        run: |
          sudo PGPASSWORD=chroma psql -h localhost -p 5432 -c 'CREATE EXTENSION IF NOT EXISTS btree_gist;' -U chroma -d template1

          echo "CRYPTO_FOLDER='./'" > local_settings.py
          echo -e "/^DEBUG =/s/= .*$/= True/\nwq" | ed settings.py 2>/dev/null
          pipenv run ./manage.py test tests/unit/
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          EMF_DISABLE_THREADS: 1
          PGPASSWORD: chroma
  emf_common_tests:
    name: EMF Common Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: "2.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools pipenv
          pipenv install --dev
        working-directory: emf-common

      - name: Run Tests
        run: pipenv run py.test
        working-directory: emf-common
  emf_common_black:
    name: EMF common black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install --upgrade pip black

      - name: check
        run: black --check ./
        working-directory: emf-common
  python_emf_agent_black:
    name: Python EMF agent black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: python -m pip install --upgrade pip black

      - name: check
        run: black --check ./
        working-directory: python-emf-agent
  python_emf_agent_unit_tests:
    name: Python EMF Agent Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: "2.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools pipenv
          pipenv install --dev
        working-directory: python-emf-agent

      - name: Run tests
        run: pipenv run nosetests
        working-directory: python-emf-agent
