name: Remove old artifacts

on:
  workflow_dispatch:
    inputs:
      age:
        description: "Cleanup duration"
        required: true
        default: "3 days"

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: ${{ github.event.inputs.age }}
