name: iml-wasm-components
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "00 01 * * *"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - beta
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Check build
        working-directory: ./iml-wasm-components
        run: cargo check --all

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true
      - run: rustup component add clippy

      - name: Run clippy
        working-directory: ./iml-wasm-components
        run: cargo clippy -- -W warnings

  rustfmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: beta
          override: true
      - run: rustup component add rustfmt

      - name: Run cargo fmt
        working-directory: ./iml-wasm-components
        run: cargo fmt --all -- --check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - beta
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Run cargo test
        working-directory: ./iml-wasm-components
        run: cargo test

  check_rpm_build:
    name: Check RPM build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Build rpm
        uses: ./.github/actions/copr-wasm
        env:
          SPEC: iml-wasm-components/iml-wasm-components.spec
          LOCAL_ONLY: true
          WORKSPACE: ${{ github.workspace }}/iml-wasm-components
